app = "n8n-uboljg"
primary_region = "cdg"

[env]
  N8N_BASIC_AUTH_ACTIVE = "true"
  N8N_BASIC_AUTH_USER = "mohamed"
  N8N_BASIC_AUTH_PASSWORD = "ضع_باسورد_من_اختيارك_هنا"
  N8N_USER_MANAGEMENT_DISABLED = "true"

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
  
